version: '3'

services:
  redis:
    image: redis:alpine3.19
    container_name: redis-bull
    command: redis-server --requirepass 1234
    ports:
      - '6379:6379'

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres-csv
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - boilerplate-queue:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}


volumes:
  boilerplate-queue: